CREATE TABLE IF NOT EXISTS users(
  id TEXT PRIMARY KEY NOT NULL,
  username TEXT NOT NULL UNIQUE, 
  password TEXT NOT NULL,
)

CREATE TABLE IF NOT EXISTS categories(
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE,
)

CREATE TABLE IF NOT EXISTS posts(
  id TEXT PRIMARY KEY NOT NULL,
  content TEXT DEFAULT "",
  authorId TEXT NOT NULL,
  FOREIGN KEY (authorId) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS posts_categories(
  category_id TEXT NOT NULL,
  post_id TEXT NOT NULL,
  FOREIGN KEY(category_id) REFERENCES categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(post_id) REFERENCES posts (id) ON UPDATE CASCADE ON DELETE CASCADE,
)